# Generated by Django 2.0.2 on 2018-02-22 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='completed_challenged',
            new_name='completed_challenges',
        ),
    ]
