# Generated by Django 2.0.2 on 2018-05-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180224_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
