# Generated by Django 2.0.2 on 2018-06-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180530_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='line_numbers',
            field=models.BooleanField(default=True),
        ),
    ]
