# Generated by Django 2.0.2 on 2018-03-05 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeResultTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_names_json', models.TextField(default='')),
                ('content_rows_json', models.TextField(default='')),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_table', to='challenges.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeSourceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creation_sql', models.TextField()),
                ('column_names_json', models.TextField(default='')),
                ('content_rows_json', models.TextField(default='')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_tables', to='challenges.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='challenges.ChallengeTopic'),
        ),
    ]
