# Generated by Django 2.0.2 on 2018-03-27 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('challenges', '0003_auto_20180327_0800'), ('challenges', '0004_auto_20180327_0805')]

    dependencies = [
        ('challenges', '0002_auto_20180306_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengetopic',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='challengetopic',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='challengetopic',
            name='long_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TopicSourceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creation_sql', models.TextField()),
                ('column_names_json', models.TextField(default='', editable=False)),
                ('content_rows_json', models.TextField(default='', editable=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_tables', to='challenges.ChallengeTopic')),
            ],
        ),
        migrations.RemoveField(
            model_name='challengesourcetable',
            name='challenge',
        ),
        migrations.DeleteModel(
            name='ChallengeSourceTable',
        ),
    ]
