# Generated by Django 2.0.2 on 2018-04-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20180327_0800_squashed_0004_auto_20180327_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='additional_info',
            new_name='hints',
        ),
        migrations.RenameField(
            model_name='challengetopic',
            old_name='long_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='challengetopic',
            old_name='short_description',
            new_name='summary',
        ),
    ]
