# Generated by Django 2.0.2 on 2018-04-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20180407_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='challengetopic',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='topicsourcetable',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='challenge',
            name='evaluation_sql',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='solution_sql',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challengetopic',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topicsourcetable',
            name='creation_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topicsourcetable',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
