# Generated by Django 2.0.2 on 2018-05-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_challengeattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='points',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
