# Generated by Django 2.0.2 on 2018-05-12 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_challenge_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicsourcetable',
            name='topics',
            field=models.ManyToManyField(related_name='source_tables', to='challenges.ChallengeTopic'),
        ),
        migrations.AlterField(
            model_name='topicsourcetable',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_table', to='challenges.ChallengeTopic'),
        ),
    ]
