# Generated by Django 2.0.2 on 2018-05-12 15:19

from django.db import migrations

def make_many_topics(apps, schema_editor):
    """
        Adds the Author object in Book.author to the
        many-to-many relationship in Book.authors
    """
    TopicSourceTable = apps.get_model('challenges', 'TopicSourceTable')

    for table in TopicSourceTable.objects.all():
        table.topics.add(table.topic)

class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_auto_20180512_1519'),
    ]

    operations = [
        migrations.RunPython(make_many_topics),

    ]
