# Generated by Django 2.0.2 on 2018-05-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_auto_20180512_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicsourcetable',
            name='topic',
        ),
    ]
